# b0gus service like ssh server should be isolated inside a container or a sandbox
# For mitigating unknown security issues.
FROM golang:latest

WORKDIR /b0gus_services
COPY . .

# install dependancies
# For Chinese users, it will be better to modify the sources.list
RUN apt update && apt upgrade && apt install -y postgresql sqlite3 make build-essential ssh vsftpd

RUN make release
# configuration for b0gus is copied from example.toml
# here we will create and try to modify the port number
RUN cp ./configs/example.toml ./configs/config.toml && cat ./configs/config.toml

## yet to evaluate these fields
# RUN make run
# EXPOSE 22