// both serializer and deserializer are created by protoc for providing service for information in http.
// like user-agent, cookie

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.21.12
// source: http_aux.proto

package services

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StrMapForHTTP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cookie        map[string]string      `protobuf:"bytes,1,rep,name=cookie,proto3" json:"cookie,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	UserAgent     string                 `protobuf:"bytes,2,opt,name=userAgent,proto3" json:"userAgent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StrMapForHTTP) Reset() {
	*x = StrMapForHTTP{}
	mi := &file_http_aux_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StrMapForHTTP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrMapForHTTP) ProtoMessage() {}

func (x *StrMapForHTTP) ProtoReflect() protoreflect.Message {
	mi := &file_http_aux_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrMapForHTTP.ProtoReflect.Descriptor instead.
func (*StrMapForHTTP) Descriptor() ([]byte, []int) {
	return file_http_aux_proto_rawDescGZIP(), []int{0}
}

func (x *StrMapForHTTP) GetCookie() map[string]string {
	if x != nil {
		return x.Cookie
	}
	return nil
}

func (x *StrMapForHTTP) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

var File_http_aux_proto protoreflect.FileDescriptor

var file_http_aux_proto_rawDesc = string([]byte{
	0x0a, 0x0e, 0x68, 0x74, 0x74, 0x70, 0x5f, 0x61, 0x75, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x9c, 0x01, 0x0a, 0x0d, 0x53, 0x74, 0x72, 0x4d, 0x61, 0x70, 0x46, 0x6f, 0x72, 0x48, 0x54,
	0x54, 0x50, 0x12, 0x32, 0x0a, 0x06, 0x63, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x53, 0x74, 0x72, 0x4d, 0x61, 0x70, 0x46, 0x6f, 0x72, 0x48, 0x54,
	0x54, 0x50, 0x2e, 0x43, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06,
	0x63, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x41, 0x67,
	0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x73, 0x65, 0x72, 0x41,
	0x67, 0x65, 0x6e, 0x74, 0x1a, 0x39, 0x0a, 0x0b, 0x43, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42,
	0x0c, 0x5a, 0x0a, 0x2e, 0x3b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_http_aux_proto_rawDescOnce sync.Once
	file_http_aux_proto_rawDescData []byte
)

func file_http_aux_proto_rawDescGZIP() []byte {
	file_http_aux_proto_rawDescOnce.Do(func() {
		file_http_aux_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_http_aux_proto_rawDesc), len(file_http_aux_proto_rawDesc)))
	})
	return file_http_aux_proto_rawDescData
}

var file_http_aux_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_http_aux_proto_goTypes = []any{
	(*StrMapForHTTP)(nil), // 0: StrMapForHTTP
	nil,                   // 1: StrMapForHTTP.CookieEntry
}
var file_http_aux_proto_depIdxs = []int32{
	1, // 0: StrMapForHTTP.cookie:type_name -> StrMapForHTTP.CookieEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_http_aux_proto_init() }
func file_http_aux_proto_init() {
	if File_http_aux_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_http_aux_proto_rawDesc), len(file_http_aux_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_http_aux_proto_goTypes,
		DependencyIndexes: file_http_aux_proto_depIdxs,
		MessageInfos:      file_http_aux_proto_msgTypes,
	}.Build()
	File_http_aux_proto = out.File
	file_http_aux_proto_goTypes = nil
	file_http_aux_proto_depIdxs = nil
}
