// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: services.proto

package services

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	TaskCheck_Start_FullMethodName      = "/rpc.TaskCheck/Start"
	TaskCheck_Terminate_FullMethodName  = "/rpc.TaskCheck/Terminate"
	TaskCheck_UpdateConf_FullMethodName = "/rpc.TaskCheck/UpdateConf"
)

// TaskCheckClient is the client API for TaskCheck service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TaskCheckClient interface {
	Start(ctx context.Context, in *ServicesRequest, opts ...grpc.CallOption) (*ServicesResponse, error)
	Terminate(ctx context.Context, in *ServicesRequest, opts ...grpc.CallOption) (*ServicesResponse, error)
	UpdateConf(ctx context.Context, in *ServicesRequest, opts ...grpc.CallOption) (*ServicesResponse, error)
}

type taskCheckClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskCheckClient(cc grpc.ClientConnInterface) TaskCheckClient {
	return &taskCheckClient{cc}
}

func (c *taskCheckClient) Start(ctx context.Context, in *ServicesRequest, opts ...grpc.CallOption) (*ServicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServicesResponse)
	err := c.cc.Invoke(ctx, TaskCheck_Start_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskCheckClient) Terminate(ctx context.Context, in *ServicesRequest, opts ...grpc.CallOption) (*ServicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServicesResponse)
	err := c.cc.Invoke(ctx, TaskCheck_Terminate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskCheckClient) UpdateConf(ctx context.Context, in *ServicesRequest, opts ...grpc.CallOption) (*ServicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServicesResponse)
	err := c.cc.Invoke(ctx, TaskCheck_UpdateConf_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskCheckServer is the server API for TaskCheck service.
// All implementations must embed UnimplementedTaskCheckServer
// for forward compatibility
type TaskCheckServer interface {
	Start(context.Context, *ServicesRequest) (*ServicesResponse, error)
	Terminate(context.Context, *ServicesRequest) (*ServicesResponse, error)
	UpdateConf(context.Context, *ServicesRequest) (*ServicesResponse, error)
	mustEmbedUnimplementedTaskCheckServer()
}

// UnimplementedTaskCheckServer must be embedded to have forward compatible implementations.
type UnimplementedTaskCheckServer struct {
}

func (UnimplementedTaskCheckServer) Start(context.Context, *ServicesRequest) (*ServicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedTaskCheckServer) Terminate(context.Context, *ServicesRequest) (*ServicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Terminate not implemented")
}
func (UnimplementedTaskCheckServer) UpdateConf(context.Context, *ServicesRequest) (*ServicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateConf not implemented")
}
func (UnimplementedTaskCheckServer) mustEmbedUnimplementedTaskCheckServer() {}

// UnsafeTaskCheckServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskCheckServer will
// result in compilation errors.
type UnsafeTaskCheckServer interface {
	mustEmbedUnimplementedTaskCheckServer()
}

func RegisterTaskCheckServer(s grpc.ServiceRegistrar, srv TaskCheckServer) {
	s.RegisterService(&TaskCheck_ServiceDesc, srv)
}

func _TaskCheck_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskCheckServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskCheck_Start_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskCheckServer).Start(ctx, req.(*ServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskCheck_Terminate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskCheckServer).Terminate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskCheck_Terminate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskCheckServer).Terminate(ctx, req.(*ServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskCheck_UpdateConf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskCheckServer).UpdateConf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskCheck_UpdateConf_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskCheckServer).UpdateConf(ctx, req.(*ServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TaskCheck_ServiceDesc is the grpc.ServiceDesc for TaskCheck service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TaskCheck_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.TaskCheck",
	HandlerType: (*TaskCheckServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Start",
			Handler:    _TaskCheck_Start_Handler,
		},
		{
			MethodName: "Terminate",
			Handler:    _TaskCheck_Terminate_Handler,
		},
		{
			MethodName: "UpdateConf",
			Handler:    _TaskCheck_UpdateConf_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services.proto",
}
