// Code generated by ./B0GUS/rdt-parser/nasty_gen.go; DO NOT EDIT.
// Generated-time: 2026-03-02 22:56:13.884 +0800 CST
package databases;
import "time"

type DnsQuery struct {
	DomainNameCreateAt time.Time `json:"domain_name_create_at" bson:"domain_name_create_at,omitempty" `
	DomainNameUpdateAt time.Time `json:"domain_name_update_at" bson:"domain_name_update_at,omitempty" `
	DomainName string `gorm:"default:0;autoCreateTime:nano;autoUpdateTime:nano;unique;not null;column:domain_name;" json:"domain_name,omitempty" bson:"domain_name,omitempty" `
	CounterForDomainName uint64 `gorm:"default:0" json:"counter_for_domain_name" bson:"counter_for_domain_name,omitempty" `
	Dqid int64 `gorm:"primaryKey;autoIncrement;not null;column:dqid;" json:"dqid,omitempty" bson:"dqid,omitempty" `
}

func (*DnsQuery) TableName() string { return "DnsQuery"; }
func (*DnsQuery) HasCounter() bool { return true; }
func (x *DnsQuery) GetPrimKey() int64 { return int64(x.Dqid) }
func (x *DnsQuery) SetOuterPrimKey(...int64) { return }
func (x *DnsQuery) UpdateCounter() {
	x.CounterForDomainName ++
}
