// Code generated by nasty_gen.go; DO NOT EDIT.
// Generated-time: 2026-02-06 21:10:03.991 +0800 CST
package databases;

import "time"

type DnsQuery struct {
	DomainNameCreateAt time.Time `json:"domain_name_create_at" bson:"domain_name_create_at,omitempty" `
	DomainNameUpdateAt time.Time `json:"domain_name_update_at" bson:"domain_name_update_at,omitempty" `
	DomainName string `gorm:"not null;default:0;autoCreateTime:nano;autoUpdateTime:nano;unique;" json:"domain_name,omitempty" bson:"domain_name,omitempty" `
	Dqid int64 `gorm:"autoIncrement;not null;primaryKey;" json:"dqid,omitempty" bson:"dqid,omitempty" `
	CounterForDomainName uint64 `gorm:"default:0" json:"counter_for_domain_name" bson:"counter_for_domain_name,omitempty" `
}

func (DnsQuery) TableName() string { return "DnsQuery"; }
func (DnsQuery) HasCounter() bool { return true; }
func (x DnsQuery) UpdateCounter() {
	x.CounterForDomainName ++
}
