// Code generated by go generate; DO NOT EDIT.
// Generated-time: 2026-02-05 22:22:01.631 +0800 CST
package databases;

import "time"

type DnsQuery struct {
	DomainNameCreateAt time.Time `json:"domain_name_create_at" bson:"domain_name_create_at,omitempty" `
	DomainNameUpdateAt time.Time `json:"domain_name_update_at" bson:"domain_name_update_at,omitempty" `
	DomainName string `gorm:"default:0;autoCreateTime:nano;autoUpdateTime:nano;unique;not null;" json:"domain_name,omitempty" bson:"domain_name,omitempty" `
	Dqid int64 `gorm:"not null;primaryKey;autoIncrement;" json:"dqid,omitempty" bson:"dqid,omitempty" `
	CounterForDomainName uint64 `gorm:"default:0" json:"counter_fordomain_name" bson:"counter_fordomain_name,omitempty" `
}


func (DnsQuery) TableName() string { return "DnsQuery"; }
func (DnsQuery) HasCounter() bool { return true; }
