// Code generated by ./b0gus/rdt-parser/nasty_gen.go; DO NOT EDIT.
// Generated-time: 2026-05-13 22:49:21.740 +0800 CST
package databases
import "time"

type HttpInfo struct {
	SessionIdCreateAt time.Time `gorm:"autoCreateTime:nano;" json:"session_id_create_at,omitempty" bson:"session_id_create_at,omitempty" `
	SessionIdUpdateAt time.Time `gorm:"autoUpdateTime:nano;" json:"session_id_update_at,omitempty" bson:"session_id_update_at,omitempty" `
	WrappedInfo []byte `gorm:"column:wrapped_info;" json:"wrapped_info,omitempty" bson:"wrapped_info,omitempty" `
	Request string `gorm:"column:request;" json:"request,omitempty" bson:"request,omitempty" `
	Method string `gorm:"not null;column:method;" json:"method,omitempty" bson:"method,omitempty" `
	Path string `gorm:"not null;column:path;" json:"path,omitempty" bson:"path,omitempty" `
	SessionId int64 `gorm:"primaryKey;column:session_id;" json:"session_id,omitempty" bson:"session_id,omitempty" `
}

func (*HttpInfo) TableName() string { return "HttpInfo" }
func (*HttpInfo) HasCounter() bool { return false }
func (x *HttpInfo) UpdateCounter() {}
func (x *HttpInfo) GetPrimKey() int64 { return int64(x.SessionId) }
func (*HttpInfo) PrimKeyName() string { return "SessionId" }
func (*HttpInfo) CreatedTSname() string { return "SessionIdCreateAt"}
func (*HttpInfo) UpdatedTSname() string { return "SessionIdUpdateAt"}
