// Code generated by nasty_gen.go; DO NOT EDIT.
// Generated-time: 2026-02-06 21:10:03.992 +0800 CST
package databases

import "time"

type PublickeyInfo struct {
	PubIdCreateAt                   time.Time                 `json:"pub_id_create_at" bson:"pub_id_create_at,omitempty" `
	PubIdUpdateAt                   time.Time                 `json:"pub_id_update_at" bson:"pub_id_update_at,omitempty" `
	OuterDefRemotePublickeyRelation []RemotePublickeyRelation `gorm:"foreignKey:Pid;" json:"-" bson:"-" `
	PubFp                           string                    `gorm:"unique;not null;" json:"pub_fp,omitempty" bson:"pub_fp,omitempty" `
	PubId                           int64                     `gorm:"primaryKey;autoCreateTime:nano;autoUpdateTime:nano;" json:"pub_id,omitempty" bson:"pub_id,omitempty" `
}

type RemotePublickeyRelation struct {
	RidRelated RemoteInfo    `gorm:"foreignKey:Rid;refences:RemoteId;constraint:OnUpdate:CASCADE,OnDelete:SET NULL;" json:"-" bson:"-" `
	PidRelated PublickeyInfo `gorm:"foreignKey:Pid;refences:PubId;constraint:OnUpdate:CASCADE,OnDelete:SET NULL;" json:"-" bson:"-" `
	Rid        int64         `gorm:"primaryKey;" bson:"rid,omitempty;" `
	Pid        int64         `gorm:"primaryKey;" bson:"pid,omitempty;" `
}

type CommandInfo struct {
	CmdCreateAt time.Time `json:"cmd_create_at" bson:"cmd_create_at,omitempty" `
	Cmd         string    `gorm:"not null;autoCreateTime:nano;" json:"cmd,omitempty" bson:"cmd,omitempty" `
	CommandId   int64     `gorm:"primaryKey;not null;" json:"command_id,omitempty" bson:"command_id,omitempty" `
}

type SshVersionInfo struct {
	IdUpdateAt                   time.Time              `json:"id_update_at" bson:"id_update_at,omitempty" `
	IdCreateAt                   time.Time              `json:"id_create_at" bson:"id_create_at,omitempty" `
	OuterDefRemoteSshverRelation []RemoteSshverRelation `gorm:"foreignKey:Sid;" json:"-" bson:"-" `
	Version                      string                 `gorm:"unique;not null;" json:"version,omitempty" bson:"version,omitempty" `
	CounterForId                 uint64                 `gorm:"default:0" json:"counter_for_id" bson:"counter_for_id,omitempty" `
	Id                           int64                  `gorm:"autoUpdateTime:nano;primaryKey;autoCreateTime:nano;" json:"id,omitempty" bson:"id,omitempty" `
}

type RemoteUsernameRelation struct {
	UidRelated                    UsernameInfo            `gorm:"foreignKey:Uid;refences:UsernameId;constraint:OnUpdate:CASCADE,OnDelete:SET NULL;" json:"-" bson:"-" `
	RidRelated                    RemoteInfo              `gorm:"foreignKey:Rid;refences:RemoteId;constraint:OnUpdate:CASCADE,OnDelete:SET NULL;" json:"-" bson:"-" `
	OuterDefRemoteCommandRelation []RemoteCommandRelation `gorm:"foreignKey:Rid;" json:"-" bson:"-" `
	Uid                           int64                   `gorm:"primaryKey;" bson:"uid,omitempty;" `
	RurId                         int64                   `gorm:"primaryKey;autoIncrement;" json:"rur_id,omitempty" bson:"rur_id,omitempty" `
	Rid                           int64                   `gorm:"primaryKey;" bson:"rid,omitempty;" `
}

type RemoteInfo struct {
	PortNumRelated                 PortInfo                 `gorm:"foreignKey:PortNum;refences:Port;constraint:OnUpdate:CASCADE,OnDelete:SET NULL;" json:"-" bson:"-" `
	AddrIdRelated                  AddrInfo                 `gorm:"foreignKey:AddrId;refences:Id;constraint:OnUpdate:CASCADE,OnDelete:SET NULL;" json:"-" bson:"-" `
	OuterDefRemoteSshverRelation   []RemoteSshverRelation   `gorm:"foreignKey:Rid;" json:"-" bson:"-" `
	OuterDefRemotePasswordRelation []RemotePasswordRelation `gorm:"foreignKey:Rid;" json:"-" bson:"-" `
	RemoteId                       int64                    `gorm:"primaryKey;" json:"remote_id,omitempty" bson:"remote_id,omitempty" `
	PortNum                        int64                    `bson:"port_num,omitempty;" `
	AddrId                         int64                    `bson:"addr_id,omitempty;" `
}

type RemoteCommandRelation struct {
	RidRelated RemoteUsernameRelation `gorm:"foreignKey:Rid;refences:RurId;constraint:OnUpdate:CASCADE,OnDelete:SET NULL;" json:"-" bson:"-" `
	CidRelated CommandInfo            `gorm:"foreignKey:Cid;refences:CommandId;constraint:OnUpdate:CASCADE,OnDelete:SET NULL;" json:"-" bson:"-" `
	Rid        int64                  `bson:"rid,omitempty;" `
	Cid        int64                  `bson:"cid,omitempty;" `
}

type RemoteSshverRelation struct {
	RidRelated RemoteInfo     `gorm:"foreignKey:Rid;refences:RemoteId;constraint:OnUpdate:CASCADE,OnDelete:SET NULL;" json:"-" bson:"-" `
	SidRelated SshVersionInfo `gorm:"foreignKey:Sid;refences:Id;constraint:OnUpdate:CASCADE,OnDelete:SET NULL;" json:"-" bson:"-" `
	Rid        int64          `gorm:"primaryKey;" bson:"rid,omitempty;" `
	Sid        int64          `gorm:"primaryKey;" bson:"sid,omitempty;" `
}

type RemotePasswordRelation struct {
	RidRelated RemoteInfo   `gorm:"foreignKey:Rid;refences:RemoteId;constraint:OnUpdate:CASCADE,OnDelete:SET NULL;" json:"-" bson:"-" `
	PidRelated PasswordInfo `gorm:"foreignKey:Pid;refences:PasswordId;constraint:OnUpdate:CASCADE,OnDelete:SET NULL;" json:"-" bson:"-" `
	Rid        int64        `gorm:"primaryKey;" bson:"rid,omitempty;" `
	Pid        int64        `gorm:"primaryKey;" bson:"pid,omitempty;" `
}

type AddrInfo struct {
	OuterDefRemoteInfo []RemoteInfo `gorm:"foreignKey:AddrId;" json:"-" bson:"-" `
	Ip                 string       `gorm:"unique;index:ip_name_idx;" json:"ip,omitempty" bson:"ip,omitempty" `
	Id                 int64        `gorm:"primaryKey;autoIncrement;not null;" json:"id,omitempty" bson:"id,omitempty" `
	CounterForIp       uint64       `gorm:"default:0" json:"counter_for_ip" bson:"counter_for_ip,omitempty" `
}

type PortInfo struct {
	OuterDefRemoteInfo []RemoteInfo `gorm:"foreignKey:PortNum;" json:"-" bson:"-" `
	Port               int64        `gorm:"primaryKey;not null;" json:"port,omitempty" bson:"port,omitempty" `
}

type UsernameInfo struct {
	UsernameIdCreateAt   time.Time `json:"username_id_create_at" bson:"username_id_create_at,omitempty" `
	UsernameIdUpdateAt   time.Time `json:"username_id_update_at" bson:"username_id_update_at,omitempty" `
	Name                 string    `gorm:"unique;" json:"name,omitempty" bson:"name,omitempty" `
	CounterForUsernameId uint64    `gorm:"default:0" json:"counter_for_username_id" bson:"counter_for_username_id,omitempty" `
	UsernameId           int64     `gorm:"primaryKey;autoCreateTime:nano;autoUpdateTime:nano;" json:"username_id,omitempty" bson:"username_id,omitempty" `
}

type PasswordInfo struct {
	PasswordIdCreateAt             time.Time                `json:"password_id_create_at" bson:"password_id_create_at,omitempty" `
	PasswordIdUpdateAt             time.Time                `json:"password_id_update_at" bson:"password_id_update_at,omitempty" `
	OuterDefRemotePasswordRelation []RemotePasswordRelation `gorm:"foreignKey:Pid;" json:"-" bson:"-" `
	Password                       string                   `gorm:"unique;" json:"password,omitempty" bson:"password,omitempty" `
	CounterForPasswordId           uint64                   `gorm:"default:0" json:"counter_for_password_id" bson:"counter_for_password_id,omitempty" `
	PasswordId                     int64                    `gorm:"primaryKey;autoCreateTime:nano;autoUpdateTime:nano;" json:"password_id,omitempty" bson:"password_id,omitempty" `
}

func (RemotePasswordRelation) TableName() string { return "RemotePasswordRelation" }
func (RemotePasswordRelation) HasCounter() bool  { return false }
func (x RemotePasswordRelation) UpdateCounter()  {}
func (AddrInfo) TableName() string               { return "AddrInfo" }
func (AddrInfo) HasCounter() bool                { return true }
func (x AddrInfo) UpdateCounter() {
	x.CounterForIp++
}
func (PortInfo) TableName() string     { return "PortInfo" }
func (PortInfo) HasCounter() bool      { return false }
func (x PortInfo) UpdateCounter()      {}
func (UsernameInfo) TableName() string { return "UsernameInfo" }
func (UsernameInfo) HasCounter() bool  { return true }
func (x UsernameInfo) UpdateCounter() {
	x.CounterForUsernameId++
}
func (PasswordInfo) TableName() string { return "PasswordInfo" }
func (PasswordInfo) HasCounter() bool  { return true }
func (x PasswordInfo) UpdateCounter() {
	x.CounterForPasswordId++
}
func (PublickeyInfo) TableName() string           { return "PublickeyInfo" }
func (PublickeyInfo) HasCounter() bool            { return false }
func (x PublickeyInfo) UpdateCounter()            {}
func (RemotePublickeyRelation) TableName() string { return "RemotePublickeyRelation" }
func (RemotePublickeyRelation) HasCounter() bool  { return false }
func (x RemotePublickeyRelation) UpdateCounter()  {}
func (CommandInfo) TableName() string             { return "CommandInfo" }
func (CommandInfo) HasCounter() bool              { return false }
func (x CommandInfo) UpdateCounter()              {}
func (SshVersionInfo) TableName() string          { return "SshVersionInfo" }
func (SshVersionInfo) HasCounter() bool           { return true }
func (x SshVersionInfo) UpdateCounter() {
	x.CounterForId++
}
func (RemoteUsernameRelation) TableName() string { return "RemoteUsernameRelation" }
func (RemoteUsernameRelation) HasCounter() bool  { return false }
func (x RemoteUsernameRelation) UpdateCounter()  {}
func (RemoteInfo) TableName() string             { return "RemoteInfo" }
func (RemoteInfo) HasCounter() bool              { return false }
func (x RemoteInfo) UpdateCounter()              {}
func (RemoteCommandRelation) TableName() string  { return "RemoteCommandRelation" }
func (RemoteCommandRelation) HasCounter() bool   { return false }
func (x RemoteCommandRelation) UpdateCounter()   {}
func (RemoteSshverRelation) TableName() string   { return "RemoteSshverRelation" }
func (RemoteSshverRelation) HasCounter() bool    { return false }
func (x RemoteSshverRelation) UpdateCounter()    {}
