// Code generated by ./B0gus/rdt-parser/nasty_gen.go; DO NOT EDIT.
// Generated-time: 2026-03-19 17:43:18.210 +0800 CST
package databases;
import "time"

type RemotePasswordRelation struct {
	RpwidRelated RemoteInfo `gorm:"foreignKey:Rpwid;references:RemoteId;constraint:OnUpdate:CASCADE,OnDelete:SET NULL;" json:"-" bson:"-" `
	PidRelated PasswordInfo `gorm:"foreignKey:Pid;references:PasswordId;constraint:OnUpdate:CASCADE,OnDelete:SET NULL;" json:"-" bson:"-" `
	Rpwid int64 `gorm:"column:rpwid;" bson:"rpwid,omitempty;" `
	Pid int64 `gorm:"column:pid;" bson:"pid,omitempty;" `
	Rprid int64 `gorm:"primaryKey;autoIncrement;column:rprid;" json:"rprid,omitempty" bson:"rprid,omitempty" `
}

type RemoteSshverRelation struct {
	RsidRelated RemoteInfo `gorm:"foreignKey:Rsid;references:RemoteId;constraint:OnUpdate:CASCADE,OnDelete:SET NULL;" json:"-" bson:"-" `
	SidRelated SshVersionInfo `gorm:"foreignKey:Sid;references:Id;constraint:OnUpdate:CASCADE,OnDelete:SET NULL;" json:"-" bson:"-" `
	Rsrid int64 `gorm:"primaryKey;autoIncrement;column:rsrid;" json:"rsrid,omitempty" bson:"rsrid,omitempty" `
	Rsid int64 `gorm:"column:rsid;" bson:"rsid,omitempty;" `
	Sid int64 `gorm:"column:sid;" bson:"sid,omitempty;" `
}

type RemoteUsernameRelation struct {
	UidRelated UsernameInfo `gorm:"foreignKey:Uid;references:UsernameId;constraint:OnUpdate:CASCADE,OnDelete:SET NULL;" json:"-" bson:"-" `
	RuidRelated RemoteInfo `gorm:"foreignKey:Ruid;references:RemoteId;constraint:OnUpdate:CASCADE,OnDelete:SET NULL;" json:"-" bson:"-" `
	RcidRelated []RemoteCommandRelation `gorm:"foreignKey:Rcid;" json:"-" bson:"-" `
	Uid int64 `gorm:"column:uid;" bson:"uid,omitempty;" `
	Rurid int64 `gorm:"primaryKey;autoIncrement;column:rurid;" json:"rurid,omitempty" bson:"rurid,omitempty" `
	Ruid int64 `gorm:"column:ruid;" bson:"ruid,omitempty;" `
}

type RemoteCommandRelation struct {
	CidRelated CommandInfo `gorm:"foreignKey:Cid;references:CommandId;constraint:OnUpdate:CASCADE,OnDelete:SET NULL;" json:"-" bson:"-" `
	RcidRelated RemoteUsernameRelation `gorm:"foreignKey:Rcid;references:Rurid;constraint:OnUpdate:CASCADE,OnDelete:SET NULL;" json:"-" bson:"-" `
	Cid int64 `gorm:"column:cid;" bson:"cid,omitempty;" `
	Rcid int64 `gorm:"column:rcid;" bson:"rcid,omitempty;" `
	Rcrid int64 `gorm:"primaryKey;not null;autoIncrement;column:rcrid;" json:"rcrid,omitempty" bson:"rcrid,omitempty" `
}

type PortInfo struct {
	PortNumRelated []RemoteInfo `gorm:"foreignKey:PortNum;" json:"-" bson:"-" `
	Port int64 `gorm:"primaryKey;not null;column:port;" json:"port,omitempty" bson:"port,omitempty" `
}

type AddrInfo struct {
	Ip string `gorm:"unique;index:ip_name_idx;column:ip;" json:"ip,omitempty" bson:"ip,omitempty" `
	Id int64 `gorm:"primaryKey;autoIncrement;not null;column:id;" json:"id,omitempty" bson:"id,omitempty" `
	CounterForIp uint64 `gorm:"default:0" json:"counter_for_ip" bson:"counter_for_ip,omitempty" `
}

type PasswordInfo struct {
	PasswordIdCreateAt time.Time `json:"password_id_create_at" bson:"password_id_create_at,omitempty" `
	PasswordIdUpdateAt time.Time `json:"password_id_update_at" bson:"password_id_update_at,omitempty" `
	Password string `gorm:"unique;column:password;" json:"password,omitempty" bson:"password,omitempty" `
	CounterForPasswordId uint64 `gorm:"default:0" json:"counter_for_password_id" bson:"counter_for_password_id,omitempty" `
	PasswordId int64 `gorm:"primaryKey;autoCreateTime:nano;autoUpdateTime:nano;column:password_id;" json:"password_id,omitempty" bson:"password_id,omitempty" `
}

type RemotePublickeyRelation struct {
	RpbidRelated RemoteInfo `gorm:"foreignKey:Rpbid;references:RemoteId;constraint:OnUpdate:CASCADE,OnDelete:SET NULL;" json:"-" bson:"-" `
	PidRelated PublickeyInfo `gorm:"foreignKey:Pid;references:PubId;constraint:OnUpdate:CASCADE,OnDelete:SET NULL;" json:"-" bson:"-" `
	Rprid int64 `gorm:"primaryKey;column:rprid;" json:"rprid,omitempty" bson:"rprid,omitempty" `
	Rpbid int64 `gorm:"column:rpbid;" bson:"rpbid,omitempty;" `
	Pid int64 `gorm:"column:pid;" bson:"pid,omitempty;" `
}

type PublickeyInfo struct {
	PubIdCreateAt time.Time `json:"pub_id_create_at" bson:"pub_id_create_at,omitempty" `
	PubIdUpdateAt time.Time `json:"pub_id_update_at" bson:"pub_id_update_at,omitempty" `
	PubFp string `gorm:"unique;not null;column:pub_fp;" json:"pub_fp,omitempty" bson:"pub_fp,omitempty" `
	PubId int64 `gorm:"autoCreateTime:nano;autoUpdateTime:nano;primaryKey;column:pub_id;" json:"pub_id,omitempty" bson:"pub_id,omitempty" `
}

type UsernameInfo struct {
	UsernameIdCreateAt time.Time `json:"username_id_create_at" bson:"username_id_create_at,omitempty" `
	UsernameIdUpdateAt time.Time `json:"username_id_update_at" bson:"username_id_update_at,omitempty" `
	UidRelated []RemoteUsernameRelation `gorm:"foreignKey:Uid;" json:"-" bson:"-" `
	Name string `gorm:"unique;column:name;" json:"name,omitempty" bson:"name,omitempty" `
	CounterForUsernameId uint64 `gorm:"default:0" json:"counter_for_username_id" bson:"counter_for_username_id,omitempty" `
	UsernameId int64 `gorm:"primaryKey;autoCreateTime:nano;autoUpdateTime:nano;column:username_id;" json:"username_id,omitempty" bson:"username_id,omitempty" `
}

type CommandInfo struct {
	CmdCreateAt time.Time `json:"cmd_create_at" bson:"cmd_create_at,omitempty" `
	CidRelated []RemoteCommandRelation `gorm:"foreignKey:Cid;" json:"-" bson:"-" `
	Cmd string `gorm:"autoCreateTime:nano;not null;column:cmd;" json:"cmd,omitempty" bson:"cmd,omitempty" `
	CommandId int64 `gorm:"primaryKey;not null;autoIncrement;column:command_id;" json:"command_id,omitempty" bson:"command_id,omitempty" `
}

type RemoteInfo struct {
	PortNumRelated PortInfo `gorm:"foreignKey:PortNum;references:Port;constraint:OnUpdate:CASCADE,OnDelete:SET NULL;" json:"-" bson:"-" `
	AddrIdRelated AddrInfo `gorm:"foreignKey:AddrId;references:Id;constraint:OnUpdate:CASCADE,OnDelete:SET NULL;" json:"-" bson:"-" `
	RpwidRelated []RemotePasswordRelation `gorm:"foreignKey:Rpwid;" json:"-" bson:"-" `
	RpbidRelated []RemotePublickeyRelation `gorm:"foreignKey:Rpbid;" json:"-" bson:"-" `
	RsidRelated []RemoteSshverRelation `gorm:"foreignKey:Rsid;" json:"-" bson:"-" `
	RuidRelated []RemoteUsernameRelation `gorm:"foreignKey:Ruid;" json:"-" bson:"-" `
	RemoteId int64 `gorm:"primaryKey;column:remote_id;" json:"remote_id,omitempty" bson:"remote_id,omitempty" `
	PortNum int64 `gorm:"column:port_num;" bson:"port_num,omitempty;" `
	AddrId int64 `gorm:"column:addr_id;" bson:"addr_id,omitempty;" `
}

type SshVersionInfo struct {
	IdCreateAt time.Time `json:"id_create_at" bson:"id_create_at,omitempty" `
	IdUpdateAt time.Time `json:"id_update_at" bson:"id_update_at,omitempty" `
	SidRelated []RemoteSshverRelation `gorm:"foreignKey:Sid;" json:"-" bson:"-" `
	Version string `gorm:"unique;not null;column:version;" json:"version,omitempty" bson:"version,omitempty" `
	CounterForId uint64 `gorm:"default:0" json:"counter_for_id" bson:"counter_for_id,omitempty" `
	Id int64 `gorm:"primaryKey;autoCreateTime:nano;autoUpdateTime:nano;column:id;" json:"id,omitempty" bson:"id,omitempty" `
}

func (*PortInfo) TableName() string { return "PortInfo"; }
func (*PortInfo) HasCounter() bool { return false; }
func (x *PortInfo) GetPrimKey() int64 { return int64(x.Port) }
func (x *PortInfo) SetOuterPrimKey(...int64) { return }
func (x *PortInfo) UpdateCounter() {}
func (*AddrInfo) TableName() string { return "AddrInfo"; }
func (*AddrInfo) HasCounter() bool { return true; }
func (x *AddrInfo) GetPrimKey() int64 { return int64(x.Id) }
func (x *AddrInfo) SetOuterPrimKey(...int64) { return }
func (x *AddrInfo) UpdateCounter() {
	x.CounterForIp ++
}
func (*PasswordInfo) TableName() string { return "PasswordInfo"; }
func (*PasswordInfo) HasCounter() bool { return true; }
func (x *PasswordInfo) GetPrimKey() int64 { return int64(x.PasswordId) }
func (x *PasswordInfo) SetOuterPrimKey(...int64) { return }
func (x *PasswordInfo) UpdateCounter() {
	x.CounterForPasswordId ++
}
func (*RemotePublickeyRelation) TableName() string { return "RemotePublickeyRelation"; }
func (*RemotePublickeyRelation) HasCounter() bool { return false; }
func (x *RemotePublickeyRelation) GetPrimKey() int64 { return int64(x.Rprid) }
func (x *RemotePublickeyRelation) SetOuterPrimKey(arr ...int64) {
	if len(arr) != 2 { panic("unmatch numbers of foreign key!") }
	x.Pid = arr[0]
	x.Rpbid = arr[1]
}
func (x *RemotePublickeyRelation) UpdateCounter() {}
func (*PublickeyInfo) TableName() string { return "PublickeyInfo"; }
func (*PublickeyInfo) HasCounter() bool { return false; }
func (x *PublickeyInfo) GetPrimKey() int64 { return int64(x.PubId) }
func (x *PublickeyInfo) SetOuterPrimKey(...int64) { return }
func (x *PublickeyInfo) UpdateCounter() {}
func (*UsernameInfo) TableName() string { return "UsernameInfo"; }
func (*UsernameInfo) HasCounter() bool { return true; }
func (x *UsernameInfo) GetPrimKey() int64 { return int64(x.UsernameId) }
func (x *UsernameInfo) SetOuterPrimKey(...int64) { return }
func (x *UsernameInfo) UpdateCounter() {
	x.CounterForUsernameId ++
}
func (*CommandInfo) TableName() string { return "CommandInfo"; }
func (*CommandInfo) HasCounter() bool { return false; }
func (x *CommandInfo) GetPrimKey() int64 { return int64(x.CommandId) }
func (x *CommandInfo) SetOuterPrimKey(...int64) { return }
func (x *CommandInfo) UpdateCounter() {}
func (*RemoteInfo) TableName() string { return "RemoteInfo"; }
func (*RemoteInfo) HasCounter() bool { return false; }
func (x *RemoteInfo) GetPrimKey() int64 { return int64(x.RemoteId) }
func (x *RemoteInfo) SetOuterPrimKey(arr ...int64) {
	if len(arr) != 2 { panic("unmatch numbers of foreign key!") }
	x.AddrId = arr[0]
	x.PortNum = arr[1]
}
func (x *RemoteInfo) UpdateCounter() {}
func (*SshVersionInfo) TableName() string { return "SshVersionInfo"; }
func (*SshVersionInfo) HasCounter() bool { return true; }
func (x *SshVersionInfo) GetPrimKey() int64 { return int64(x.Id) }
func (x *SshVersionInfo) SetOuterPrimKey(...int64) { return }
func (x *SshVersionInfo) UpdateCounter() {
	x.CounterForId ++
}
func (*RemotePasswordRelation) TableName() string { return "RemotePasswordRelation"; }
func (*RemotePasswordRelation) HasCounter() bool { return false; }
func (x *RemotePasswordRelation) GetPrimKey() int64 { return int64(x.Rprid) }
func (x *RemotePasswordRelation) SetOuterPrimKey(arr ...int64) {
	if len(arr) != 2 { panic("unmatch numbers of foreign key!") }
	x.Pid = arr[0]
	x.Rpwid = arr[1]
}
func (x *RemotePasswordRelation) UpdateCounter() {}
func (*RemoteSshverRelation) TableName() string { return "RemoteSshverRelation"; }
func (*RemoteSshverRelation) HasCounter() bool { return false; }
func (x *RemoteSshverRelation) GetPrimKey() int64 { return int64(x.Rsrid) }
func (x *RemoteSshverRelation) SetOuterPrimKey(arr ...int64) {
	if len(arr) != 2 { panic("unmatch numbers of foreign key!") }
	x.Rsid = arr[0]
	x.Sid = arr[1]
}
func (x *RemoteSshverRelation) UpdateCounter() {}
func (*RemoteUsernameRelation) TableName() string { return "RemoteUsernameRelation"; }
func (*RemoteUsernameRelation) HasCounter() bool { return false; }
func (x *RemoteUsernameRelation) GetPrimKey() int64 { return int64(x.Rurid) }
func (x *RemoteUsernameRelation) SetOuterPrimKey(arr ...int64) {
	if len(arr) != 2 { panic("unmatch numbers of foreign key!") }
	x.Ruid = arr[0]
	x.Uid = arr[1]
}
func (x *RemoteUsernameRelation) UpdateCounter() {}
func (*RemoteCommandRelation) TableName() string { return "RemoteCommandRelation"; }
func (*RemoteCommandRelation) HasCounter() bool { return false; }
func (x *RemoteCommandRelation) GetPrimKey() int64 { return int64(x.Rcrid) }
func (x *RemoteCommandRelation) SetOuterPrimKey(arr ...int64) {
	if len(arr) != 2 { panic("unmatch numbers of foreign key!") }
	x.Cid = arr[0]
	x.Rcid = arr[1]
}
func (x *RemoteCommandRelation) UpdateCounter() {}
