// Code generated by ./b0gus/rdt-parser/nasty_gen.go; DO NOT EDIT.
// Generated-time: 2026-03-28 22:32:14.926 +0800 CST
package databases
import "time"

type RemoteCommandRelation struct {
	CidRelated CommandInfo `gorm:"foreignKey:Cid;references:CommandId;constraint:OnUpdate:CASCADE,OnDelete:SET NULL;" json:"-" bson:"-" `
	SessionId int64 `gorm:"not null;column:session_id;" json:"session_id,omitempty" bson:"session_id,omitempty" `
	Cid int64 `gorm:"column:cid;" bson:"cid,omitempty;" `
	Rcid int64 `gorm:"primaryKey;column:rcid;" json:"rcid,omitempty" bson:"rcid,omitempty" `
}

type SshVersionInfo struct {
	IdCreateAt time.Time `gorm:"autoCreateTime:nano;" json:"id_create_at,omitempty" bson:"id_create_at,omitempty" `
	IdUpdateAt time.Time `gorm:"autoUpdateTime:nano;" json:"id_update_at,omitempty" bson:"id_update_at,omitempty" `
	SidRelated []RemoteSshverRelation `gorm:"foreignKey:Sid" json:"-" bson:"-" `
	Version string `gorm:"unique;not null;column:version;" json:"version,omitempty" bson:"version,omitempty" `
	CounterForId uint64 `gorm:"default:0" json:"counter_for_id,omitempty" bson:"counter_for_id,omitempty" `
	Id int64 `gorm:"primaryKey;column:id;" json:"id,omitempty" bson:"id,omitempty" `
}

type RemoteSshverRelation struct {
	SidRelated SshVersionInfo `gorm:"foreignKey:Sid;references:Id;constraint:OnUpdate:CASCADE,OnDelete:SET NULL;" json:"-" bson:"-" `
	Rsid int64 `gorm:"primaryKey;column:rsid;" json:"rsid,omitempty" bson:"rsid,omitempty" `
	SessionId int64 `gorm:"not null;column:session_id;" json:"session_id,omitempty" bson:"session_id,omitempty" `
	Sid int64 `gorm:"column:sid;" bson:"sid,omitempty;" `
}

type UsernameInfo struct {
	UsernameIdCreateAt time.Time `gorm:"autoCreateTime:nano;" json:"username_id_create_at,omitempty" bson:"username_id_create_at,omitempty" `
	UsernameIdUpdateAt time.Time `gorm:"autoUpdateTime:nano;" json:"username_id_update_at,omitempty" bson:"username_id_update_at,omitempty" `
	UidRelated []RemoteUsernameRelation `gorm:"foreignKey:Uid" json:"-" bson:"-" `
	Name string `gorm:"unique;column:name;" json:"name,omitempty" bson:"name,omitempty" `
	CounterForUsernameId uint64 `gorm:"default:0" json:"counter_for_username_id,omitempty" bson:"counter_for_username_id,omitempty" `
	UsernameId int64 `gorm:"primaryKey;column:username_id;" json:"username_id,omitempty" bson:"username_id,omitempty" `
}

type RemoteUsernameRelation struct {
	UidRelated UsernameInfo `gorm:"foreignKey:Uid;references:UsernameId;constraint:OnUpdate:CASCADE,OnDelete:SET NULL;" json:"-" bson:"-" `
	Ruid int64 `gorm:"primaryKey;column:ruid;" json:"ruid,omitempty" bson:"ruid,omitempty" `
	SessionId int64 `gorm:"not null;column:session_id;" json:"session_id,omitempty" bson:"session_id,omitempty" `
	Uid int64 `gorm:"column:uid;" bson:"uid,omitempty;" `
}

type RemotePublickeyRelation struct {
	PidRelated PublickeyInfo `gorm:"foreignKey:Pid;references:PubId;constraint:OnUpdate:CASCADE,OnDelete:SET NULL;" json:"-" bson:"-" `
	Rpubid int64 `gorm:"primaryKey;column:rpubid;" json:"rpubid,omitempty" bson:"rpubid,omitempty" `
	SessionId int64 `gorm:"not null;column:session_id;" json:"session_id,omitempty" bson:"session_id,omitempty" `
	Pid int64 `gorm:"column:pid;" bson:"pid,omitempty;" `
}

type AddrInfo struct {
	Ip string `gorm:"unique;index:ip_name_idx;column:ip;" json:"ip,omitempty" bson:"ip,omitempty" `
	CounterForIp uint64 `gorm:"default:0" json:"counter_for_ip,omitempty" bson:"counter_for_ip,omitempty" `
	Id int64 `gorm:"primaryKey;autoIncrement;not null;column:id;" json:"id,omitempty" bson:"id,omitempty" `
}

type PortInfo struct {
	Port int64 `gorm:"primaryKey;not null;column:port;" json:"port,omitempty" bson:"port,omitempty" `
}

type PasswordInfo struct {
	PasswordIdCreateAt time.Time `gorm:"autoCreateTime:nano;" json:"password_id_create_at,omitempty" bson:"password_id_create_at,omitempty" `
	PasswordIdUpdateAt time.Time `gorm:"autoUpdateTime:nano;" json:"password_id_update_at,omitempty" bson:"password_id_update_at,omitempty" `
	PidRelated []RemotePasswordRelation `gorm:"foreignKey:Pid" json:"-" bson:"-" `
	Password string `gorm:"unique;column:password;" json:"password,omitempty" bson:"password,omitempty" `
	CounterForPasswordId uint64 `gorm:"default:0" json:"counter_for_password_id,omitempty" bson:"counter_for_password_id,omitempty" `
	PasswordId int64 `gorm:"primaryKey;column:password_id;" json:"password_id,omitempty" bson:"password_id,omitempty" `
}

type RemotePasswordRelation struct {
	PidRelated PasswordInfo `gorm:"foreignKey:Pid;references:PasswordId;constraint:OnUpdate:CASCADE,OnDelete:SET NULL;" json:"-" bson:"-" `
	Pid int64 `gorm:"column:pid;" bson:"pid,omitempty;" `
	Rpwdid int64 `gorm:"primaryKey;column:rpwdid;" json:"rpwdid,omitempty" bson:"rpwdid,omitempty" `
	SessionId int64 `gorm:"not null;column:session_id;" json:"session_id,omitempty" bson:"session_id,omitempty" `
}

type PublickeyInfo struct {
	PubIdCreateAt time.Time `gorm:"autoCreateTime:nano;" json:"pub_id_create_at,omitempty" bson:"pub_id_create_at,omitempty" `
	PubIdUpdateAt time.Time `gorm:"autoUpdateTime:nano;" json:"pub_id_update_at,omitempty" bson:"pub_id_update_at,omitempty" `
	PubFp []byte `gorm:"unique;not null;column:pub_fp;" json:"pub_fp,omitempty" bson:"pub_fp,omitempty" `
	PidRelated []RemotePublickeyRelation `gorm:"foreignKey:Pid" json:"-" bson:"-" `
	PubId int64 `gorm:"primaryKey;column:pub_id;" json:"pub_id,omitempty" bson:"pub_id,omitempty" `
}

type CommandInfo struct {
	CmdCreateAt time.Time `gorm:"autoCreateTime:nano;" json:"cmd_create_at,omitempty" bson:"cmd_create_at,omitempty" `
	CidRelated []RemoteCommandRelation `gorm:"foreignKey:Cid" json:"-" bson:"-" `
	Cmd string `gorm:"not null;column:cmd;" json:"cmd,omitempty" bson:"cmd,omitempty" `
	CommandId int64 `gorm:"autoIncrement;primaryKey;not null;column:command_id;" json:"command_id,omitempty" bson:"command_id,omitempty" `
}

func (*PublickeyInfo) TableName() string { return "PublickeyInfo" }
func (*PublickeyInfo) HasCounter() bool { return false }
func (x *PublickeyInfo) UpdateCounter() {}
func (x *PublickeyInfo) GetPrimKey() int64 { return int64(x.PubId) }
func (*PublickeyInfo) PrimKeyName() string { return "PubId" }
func (*PublickeyInfo) CreatedTSname() string { return "PubIdCreateAt"}
func (*PublickeyInfo) UpdatedTSname() string { return "PubIdUpdateAt"}
func (*CommandInfo) TableName() string { return "CommandInfo" }
func (*CommandInfo) HasCounter() bool { return false }
func (x *CommandInfo) UpdateCounter() {}
func (x *CommandInfo) GetPrimKey() int64 { return int64(x.CommandId) }
func (*CommandInfo) PrimKeyName() string { return "CommandId" }
func (*CommandInfo) CreatedTSname() string { return "CmdCreateAt"}
func (*CommandInfo) UpdatedTSname() string { return ""}
func (*RemoteCommandRelation) TableName() string { return "RemoteCommandRelation" }
func (*RemoteCommandRelation) HasCounter() bool { return false }
func (x *RemoteCommandRelation) UpdateCounter() {}
func (x *RemoteCommandRelation) GetPrimKey() int64 { return int64(x.Rcid) }
func (*RemoteCommandRelation) PrimKeyName() string { return "Rcid" }
func (*RemoteCommandRelation) CreatedTSname() string { return ""}
func (*RemoteCommandRelation) UpdatedTSname() string { return ""}
func (*SshVersionInfo) TableName() string { return "SshVersionInfo" }
func (*SshVersionInfo) HasCounter() bool { return true }
func (x *SshVersionInfo) UpdateCounter() {
	x.CounterForId ++
}
func (x *SshVersionInfo) GetPrimKey() int64 { return int64(x.Id) }
func (*SshVersionInfo) PrimKeyName() string { return "Id" }
func (*SshVersionInfo) CreatedTSname() string { return "IdCreateAt"}
func (*SshVersionInfo) UpdatedTSname() string { return "IdUpdateAt"}
func (*RemoteSshverRelation) TableName() string { return "RemoteSshverRelation" }
func (*RemoteSshverRelation) HasCounter() bool { return false }
func (x *RemoteSshverRelation) UpdateCounter() {}
func (x *RemoteSshverRelation) GetPrimKey() int64 { return int64(x.Rsid) }
func (*RemoteSshverRelation) PrimKeyName() string { return "Rsid" }
func (*RemoteSshverRelation) CreatedTSname() string { return ""}
func (*RemoteSshverRelation) UpdatedTSname() string { return ""}
func (*UsernameInfo) TableName() string { return "UsernameInfo" }
func (*UsernameInfo) HasCounter() bool { return true }
func (x *UsernameInfo) UpdateCounter() {
	x.CounterForUsernameId ++
}
func (x *UsernameInfo) GetPrimKey() int64 { return int64(x.UsernameId) }
func (*UsernameInfo) PrimKeyName() string { return "UsernameId" }
func (*UsernameInfo) CreatedTSname() string { return "UsernameIdCreateAt"}
func (*UsernameInfo) UpdatedTSname() string { return "UsernameIdUpdateAt"}
func (*RemoteUsernameRelation) TableName() string { return "RemoteUsernameRelation" }
func (*RemoteUsernameRelation) HasCounter() bool { return false }
func (x *RemoteUsernameRelation) UpdateCounter() {}
func (x *RemoteUsernameRelation) GetPrimKey() int64 { return int64(x.Ruid) }
func (*RemoteUsernameRelation) PrimKeyName() string { return "Ruid" }
func (*RemoteUsernameRelation) CreatedTSname() string { return ""}
func (*RemoteUsernameRelation) UpdatedTSname() string { return ""}
func (*RemotePublickeyRelation) TableName() string { return "RemotePublickeyRelation" }
func (*RemotePublickeyRelation) HasCounter() bool { return false }
func (x *RemotePublickeyRelation) UpdateCounter() {}
func (x *RemotePublickeyRelation) GetPrimKey() int64 { return int64(x.Rpubid) }
func (*RemotePublickeyRelation) PrimKeyName() string { return "Rpubid" }
func (*RemotePublickeyRelation) CreatedTSname() string { return ""}
func (*RemotePublickeyRelation) UpdatedTSname() string { return ""}
func (*AddrInfo) TableName() string { return "AddrInfo" }
func (*AddrInfo) HasCounter() bool { return true }
func (x *AddrInfo) UpdateCounter() {
	x.CounterForIp ++
}
func (x *AddrInfo) GetPrimKey() int64 { return int64(x.Id) }
func (*AddrInfo) PrimKeyName() string { return "Id" }
func (*AddrInfo) CreatedTSname() string { return ""}
func (*AddrInfo) UpdatedTSname() string { return ""}
func (*PortInfo) TableName() string { return "PortInfo" }
func (*PortInfo) HasCounter() bool { return false }
func (x *PortInfo) UpdateCounter() {}
func (x *PortInfo) GetPrimKey() int64 { return int64(x.Port) }
func (*PortInfo) PrimKeyName() string { return "Port" }
func (*PortInfo) CreatedTSname() string { return ""}
func (*PortInfo) UpdatedTSname() string { return ""}
func (*PasswordInfo) TableName() string { return "PasswordInfo" }
func (*PasswordInfo) HasCounter() bool { return true }
func (x *PasswordInfo) UpdateCounter() {
	x.CounterForPasswordId ++
}
func (x *PasswordInfo) GetPrimKey() int64 { return int64(x.PasswordId) }
func (*PasswordInfo) PrimKeyName() string { return "PasswordId" }
func (*PasswordInfo) CreatedTSname() string { return "PasswordIdCreateAt"}
func (*PasswordInfo) UpdatedTSname() string { return "PasswordIdUpdateAt"}
func (*RemotePasswordRelation) TableName() string { return "RemotePasswordRelation" }
func (*RemotePasswordRelation) HasCounter() bool { return false }
func (x *RemotePasswordRelation) UpdateCounter() {}
func (x *RemotePasswordRelation) GetPrimKey() int64 { return int64(x.Rpwdid) }
func (*RemotePasswordRelation) PrimKeyName() string { return "Rpwdid" }
func (*RemotePasswordRelation) CreatedTSname() string { return ""}
func (*RemotePasswordRelation) UpdatedTSname() string { return ""}
