[server_config]
# will store pem in `configs` directory
pem_name = "ssh_host_pem"
listen_addr = "localhost"
# it might be identical to run this program in port 22 as a bogus ssh server
# but for non-root user, binding to port < 1024 is not allowed
# so we will use docker in the future
listen_port = 2333
service_name = "ssh"
max_client_num = 32
client_conn_timeout = 180  # in seconds

# only store `ip, username, password, access time and public key` info
permit_login = true
empty_shell = true
# just repeat what user inputs back to the terminal
# TODO: add more response types later
response_type = "repeater"

# have not deployed in distributed database yet
# leave this field as true at present
is_local_database = true

# yet to have a checking/filtering mechanism to determine 
# whether database_addr:database_port is requried
database_name = ""
database_addr = "localhost"
database_port = 5432

# this domain is used for different sql like SQLite.
# Unlike PostgreSQL, SQLite stores data in a `db` file whose path is 
# explictly given
database_path = "/home/bot/Projects/SQLite/nasty-ssh-client.db"

has_database_admin = true
admin_name = "Literally,Postgres"
admin_pass = "YouPassw0rdShouldBeStrongAndInvisible2Others"
