############################### NOTICE ###############################
# This is an example configuration. You should create your own `config.toml` in the
# same directory so that b0gus can run as what you expect it to obey.
############################### NOTICE ###############################
[server_config]
# Will store pem in the same `configs` directory
pem_name = "host.pem"

# It might be identical to run this program in port 22 as a b0gus ssh server
# but for non-root user, binding to port < 1024 is not allowed
# so we will use docker in the future to achieve such goal
[server_config.ssh]
    listen_addr = "localhost"
    listen_port = 2333

    ## strategy on ssh server configuration
    max_client_num = 32
    client_conn_timeout = 180 # time-unit is second
    # only store `ip, username, password, access time and public key` information
    # TODO: set them as strategy
    permit_login = true
    empty_shell = true
    # just repeat what user inputs back to the terminal
    # TODO: add more response types which represent certain strategy 
    # for interacting with malicious clients later
    response_type = "repeater"

[server_config.telnet]
    listen_addr = "localhost"
    listen_port = 23333
    

[server_config.database]
    # Yet to have a checking/filtering mechanism to determine 
    # whether database_addr:database_port is requried
    database_type = "PostgreSQL"
    database_name = "postgres"
    database_addr = "localhost"
    database_port = 5432
    database_admin_name = "postgres"
    database_admin_password = "YouPassw0rdShouldBeStrongAndInvisible2Others"
    # this redundant domain is used for different sql like SQLite
    # Unlike PostgreSQL, SQLite stores data in a `db` file whose path is 
    # explictly given. And default directory is set to `assets`, where stores the database
    # file that **have to be created** manually or by automated scripts
    # Lastly, the corresponding dataname should fill with `sqlite`, `SQLITE`, or `SQLite`
    database_path = "nasty-ssh-client.db"
