// Code Generated by ./b0gus/rdt-parser/nasty_gen.go. DO NOT EDIT.
// Package configs
// Generated-time: 2026-03-19 17:43:18.211 +0800 CST

package configs

import "b0gus/databases"

var RecRelationMap = map[string]map[string]any{

	"AddrInfo": {
		"PortInfo": &databases.RemoteInfo{},
	},
	"RemoteInfo": {
		"PasswordInfo": &databases.RemotePasswordRelation{},
		"PublickeyInfo": &databases.RemotePublickeyRelation{},
		"SshVersionInfo": &databases.RemoteSshverRelation{},
		"UsernameInfo": &databases.RemoteUsernameRelation{},
	},
	"PasswordInfo": {
		"RemoteInfo": &databases.RemotePasswordRelation{},
	},
	"PublickeyInfo": {
		"RemoteInfo": &databases.RemotePublickeyRelation{},
	},
	"SshVersionInfo": {
		"RemoteInfo": &databases.RemoteSshverRelation{},
	},
	"UsernameInfo": {
		"RemoteInfo": &databases.RemoteUsernameRelation{},
	},
	"RemoteUsernameRelation": {
		"CommandInfo": &databases.RemoteCommandRelation{},
	},
	"PortInfo": {
		"AddrInfo": &databases.RemoteInfo{},
	},
	"CommandInfo": {
		"RemoteUsernameRelation": &databases.RemoteCommandRelation{},
	},
}