// Code Generated by ./B0GUS/rdt-parser/nasty_gen.go. DO NOT EDIT.
// Generated-time: 2026-03-02 22:56:13.886 +0800 CST
package configs

import b0gus_databases "b0gus/databases"

var RecRelationMap = map[string]map[string]any{

	"UsernameInfo": {
		"RemoteInfo": &b0gus_databases.RemoteUsernameRelation{},
	},
	"RemoteUsernameRelation": {
		"CommandInfo": &b0gus_databases.RemoteCommandRelation{},
	},
	"AddrInfo": {
		"PortInfo": &b0gus_databases.RemoteInfo{},
	},
	"SshVersionInfo": {
		"RemoteInfo": &b0gus_databases.RemoteSshverRelation{},
	},
	"PublickeyInfo": {
		"RemoteInfo": &b0gus_databases.RemotePublickeyRelation{},
	},
	"CommandInfo": {
		"RemoteUsernameRelation": &b0gus_databases.RemoteCommandRelation{},
	},
	"PortInfo": {
		"AddrInfo": &b0gus_databases.RemoteInfo{},
	},
	"RemoteInfo": {
		"SshVersionInfo": &b0gus_databases.RemoteSshverRelation{},
		"PasswordInfo": &b0gus_databases.RemotePasswordRelation{},
		"UsernameInfo": &b0gus_databases.RemoteUsernameRelation{},
		"PublickeyInfo": &b0gus_databases.RemotePublickeyRelation{},
	},
	"PasswordInfo": {
		"RemoteInfo": &b0gus_databases.RemotePasswordRelation{},
	},
}