// Code generated by MockGen. DO NOT EDIT.
// Source: databases/db_aux.go

// Package mock is a generated GoMock package.
package mock

import (
	configs "b0gus/configs"
	databases "b0gus/databases"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDBstruct is a mock of DBstruct interface.
type MockDBstruct struct {
	ctrl     *gomock.Controller
	recorder *MockDBstructMockRecorder
}

// MockDBstructMockRecorder is the mock recorder for MockDBstruct.
type MockDBstructMockRecorder struct {
	mock *MockDBstruct
}

// NewMockDBstruct creates a new mock instance.
func NewMockDBstruct(ctrl *gomock.Controller) *MockDBstruct {
	mock := &MockDBstruct{ctrl: ctrl}
	mock.recorder = &MockDBstructMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBstruct) EXPECT() *MockDBstructMockRecorder {
	return m.recorder
}

// CreatedTSname mocks base method.
func (m *MockDBstruct) CreatedTSname() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatedTSname")
	ret0, _ := ret[0].(string)
	return ret0
}

// CreatedTSname indicates an expected call of CreatedTSname.
func (mr *MockDBstructMockRecorder) CreatedTSname() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatedTSname", reflect.TypeOf((*MockDBstruct)(nil).CreatedTSname))
}

// GetPrimKey mocks base method.
func (m *MockDBstruct) GetPrimKey() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPrimKey")
	ret0, _ := ret[0].(int64)
	return ret0
}

// GetPrimKey indicates an expected call of GetPrimKey.
func (mr *MockDBstructMockRecorder) GetPrimKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPrimKey", reflect.TypeOf((*MockDBstruct)(nil).GetPrimKey))
}

// HasCounter mocks base method.
func (m *MockDBstruct) HasCounter() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasCounter")
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasCounter indicates an expected call of HasCounter.
func (mr *MockDBstructMockRecorder) HasCounter() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasCounter", reflect.TypeOf((*MockDBstruct)(nil).HasCounter))
}

// PrimKeyName mocks base method.
func (m *MockDBstruct) PrimKeyName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrimKeyName")
	ret0, _ := ret[0].(string)
	return ret0
}

// PrimKeyName indicates an expected call of PrimKeyName.
func (mr *MockDBstructMockRecorder) PrimKeyName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrimKeyName", reflect.TypeOf((*MockDBstruct)(nil).PrimKeyName))
}

// TableName mocks base method.
func (m *MockDBstruct) TableName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TableName")
	ret0, _ := ret[0].(string)
	return ret0
}

// TableName indicates an expected call of TableName.
func (mr *MockDBstructMockRecorder) TableName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TableName", reflect.TypeOf((*MockDBstruct)(nil).TableName))
}

// UpdateCounter mocks base method.
func (m *MockDBstruct) UpdateCounter() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateCounter")
}

// UpdateCounter indicates an expected call of UpdateCounter.
func (mr *MockDBstructMockRecorder) UpdateCounter() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCounter", reflect.TypeOf((*MockDBstruct)(nil).UpdateCounter))
}

// UpdatedTSname mocks base method.
func (m *MockDBstruct) UpdatedTSname() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatedTSname")
	ret0, _ := ret[0].(string)
	return ret0
}

// UpdatedTSname indicates an expected call of UpdatedTSname.
func (mr *MockDBstructMockRecorder) UpdatedTSname() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatedTSname", reflect.TypeOf((*MockDBstruct)(nil).UpdatedTSname))
}

// MockDBhandler is a mock of DBhandler interface.
type MockDBhandler struct {
	ctrl     *gomock.Controller
	recorder *MockDBhandlerMockRecorder
}

// MockDBhandlerMockRecorder is the mock recorder for MockDBhandler.
type MockDBhandlerMockRecorder struct {
	mock *MockDBhandler
}

// NewMockDBhandler creates a new mock instance.
func NewMockDBhandler(ctrl *gomock.Controller) *MockDBhandler {
	mock := &MockDBhandler{ctrl: ctrl}
	mock.recorder = &MockDBhandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBhandler) EXPECT() *MockDBhandlerMockRecorder {
	return m.recorder
}

// AlterDatabaseHandler mocks base method.
func (m *MockDBhandler) AlterDatabaseHandler(dstDB any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AlterDatabaseHandler", dstDB)
}

// AlterDatabaseHandler indicates an expected call of AlterDatabaseHandler.
func (mr *MockDBhandlerMockRecorder) AlterDatabaseHandler(dstDB interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AlterDatabaseHandler", reflect.TypeOf((*MockDBhandler)(nil).AlterDatabaseHandler), dstDB)
}

// CreateOrUpdateItem mocks base method.
func (m *MockDBhandler) CreateOrUpdateItem(cond, goal databases.DBstruct) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrUpdateItem", cond, goal)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrUpdateItem indicates an expected call of CreateOrUpdateItem.
func (mr *MockDBhandlerMockRecorder) CreateOrUpdateItem(cond, goal interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrUpdateItem", reflect.TypeOf((*MockDBhandler)(nil).CreateOrUpdateItem), cond, goal)
}

// CreateOrUpdateItemsInSeq mocks base method.
func (m *MockDBhandler) CreateOrUpdateItemsInSeq(arg0 ...databases.DBstruct) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateOrUpdateItemsInSeq", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrUpdateItemsInSeq indicates an expected call of CreateOrUpdateItemsInSeq.
func (mr *MockDBhandlerMockRecorder) CreateOrUpdateItemsInSeq(arg0 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrUpdateItemsInSeq", reflect.TypeOf((*MockDBhandler)(nil).CreateOrUpdateItemsInSeq), arg0...)
}

// CreateTable mocks base method.
func (m *MockDBhandler) CreateTable(structures ...databases.DBstruct) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range structures {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateTable", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTable indicates an expected call of CreateTable.
func (mr *MockDBhandlerMockRecorder) CreateTable(structures ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTable", reflect.TypeOf((*MockDBhandler)(nil).CreateTable), structures...)
}

// Setup mocks base method.
func (m *MockDBhandler) Setup(conf *configs.RecDBConfig, structures ...databases.DBstruct) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{conf}
	for _, a := range structures {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Setup", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Setup indicates an expected call of Setup.
func (mr *MockDBhandlerMockRecorder) Setup(conf interface{}, structures ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{conf}, structures...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Setup", reflect.TypeOf((*MockDBhandler)(nil).Setup), varargs...)
}
