// Code generated by MockGen. DO NOT EDIT.
// Source: services/abstract_tcpip.go

// Package mock is a generated GoMock package.
package mock

import (
	net "net"
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAbsServNetAux is a mock of AbsServNetAux interface.
type MockAbsServNetAux struct {
	ctrl     *gomock.Controller
	recorder *MockAbsServNetAuxMockRecorder
}

// MockAbsServNetAuxMockRecorder is the mock recorder for MockAbsServNetAux.
type MockAbsServNetAuxMockRecorder struct {
	mock *MockAbsServNetAux
}

// NewMockAbsServNetAux creates a new mock instance.
func NewMockAbsServNetAux(ctrl *gomock.Controller) *MockAbsServNetAux {
	mock := &MockAbsServNetAux{ctrl: ctrl}
	mock.recorder = &MockAbsServNetAuxMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAbsServNetAux) EXPECT() *MockAbsServNetAuxMockRecorder {
	return m.recorder
}

// InvokeForICMPtask mocks base method.
func (m *MockAbsServNetAux) InvokeForICMPtask(addr net.Addr, payload []byte) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InvokeForICMPtask", addr, payload)
}

// InvokeForICMPtask indicates an expected call of InvokeForICMPtask.
func (mr *MockAbsServNetAuxMockRecorder) InvokeForICMPtask(addr, payload interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvokeForICMPtask", reflect.TypeOf((*MockAbsServNetAux)(nil).InvokeForICMPtask), addr, payload)
}

// InvokeForTCPtask mocks base method.
func (m *MockAbsServNetAux) InvokeForTCPtask(conn net.Conn) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InvokeForTCPtask", conn)
}

// InvokeForTCPtask indicates an expected call of InvokeForTCPtask.
func (mr *MockAbsServNetAuxMockRecorder) InvokeForTCPtask(conn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvokeForTCPtask", reflect.TypeOf((*MockAbsServNetAux)(nil).InvokeForTCPtask), conn)
}

// InvokeForUDPtask mocks base method.
func (m *MockAbsServNetAux) InvokeForUDPtask(addr net.Addr, payload []byte) []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvokeForUDPtask", addr, payload)
	ret0, _ := ret[0].([]byte)
	return ret0
}

// InvokeForUDPtask indicates an expected call of InvokeForUDPtask.
func (mr *MockAbsServNetAuxMockRecorder) InvokeForUDPtask(addr, payload interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvokeForUDPtask", reflect.TypeOf((*MockAbsServNetAux)(nil).InvokeForUDPtask), addr, payload)
}

// ServeHTTP mocks base method.
func (m *MockAbsServNetAux) ServeHTTP(arg0 http.ResponseWriter, arg1 *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ServeHTTP", arg0, arg1)
}

// ServeHTTP indicates an expected call of ServeHTTP.
func (mr *MockAbsServNetAuxMockRecorder) ServeHTTP(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServeHTTP", reflect.TypeOf((*MockAbsServNetAux)(nil).ServeHTTP), arg0, arg1)
}
