#!/usr/bin/env sh
# SPDX-LICENSE-IDENTIFIER: 3-Clauses-BSD

# I don't think this certificates would help

#### check for dependencies programs
# shellcheck disable=SC3040
set -o pipefail
one_test="$(openssl --version | grep -in 'openssl')"
if [ -z "$one_test" ]; then
    echo "This shell script requires \`openssl\`"
    exit 1
fi

#### prepare for the backup directory
CURR_USER="$(whoami)"
DEFAULT_PATH="$HOME/.b0gus-ca/"
KEY_REL_PATH="private/b0gus_root_$CURR_USER.key.pem"
CERT_REL_PATH="certs/b0gus_root_$CURR_USER.crt.pem"

#### TODO precisely check for if local directory already has certs or keys by verifying if the cert is signed by pri-key
if [ -f "$DEFAULT_PATH/$KEY_REL_PATH" ] && [ -f "$DEFAULT_PATH/$CERT_REL_PATH" ]; then
    echo "There is already (key, cert) under $DEFAULT_PATH."
    exit 1
fi

#### check for environment variables
if [ -z "$ENV_EMAIL" ]; then
    ENV_EMAIL="site-security@redhat.com"
fi
if [ -z "$ENV_COMMON_NAME" ]; then
    ENV_COMMON_NAME="kisfg"
fi
if [ -z "$ENV_ORGANIZATION_NAME" ]; then
    ENV_ORGANIZATION_NAME="b0gus Tech"
fi
if [ -z "$ENV_ORGANIZATION_UNIT_NAME" ]; then
    ENV_ORGANIZATION_UNIT_NAME="TGW Group"
fi
if [ -z "$ENV_COUNTRY_OR_ZONE_NAME" ]; then
    ENV_COUNTRY_OR_ZONE_NAME="cn"
fi
if [ -z "$ENV_STATE_OR_PROVINCE_NAME" ]; then
    ENV_STATE_OR_PROVINCE_NAME="Hubei"
fi
if [ -z "$ENV_LOCALITY_NAME" ]; then
    ENV_LOCALITY_NAME="Wuhan"
fi

#### set up error-filters
set -eu
mkdir -p "$DEFAULT_PATH/"

#### switch current working directory
cd "$DEFAULT_PATH"
mkdir -p certs crl newcerts private
curr_dir="$(pwd)"

#### set privilege and create necessary files
chmod 700 "$DEFAULT_PATH/private"

#### index.txt, serial, and ca.cnf.
touch "$DEFAULT_PATH/index.txt"
echo 1000 > "$DEFAULT_PATH/serial"
ca_cnf_dir="$DEFAULT_PATH/ca.cnf"
#### generate ca.cnf file.
cat > "$ca_cnf_dir" << END_OF_STREAM
# this ca configuration file is auto-generated by register_trusted_pem.sh.
[ ca ]
default_ca = CA_default

[ CA_default ]
dir             = $curr_dir
certs           = $curr_dir/certs
crl_dir         = $curr_dir/crl
new_certs_dir   = $curr_dir/newcerts
database        = $curr_dir/index.txt
serial          = $curr_dir/serial
RANDFILE        = $curr_dir/private/.rand

private_key     = $curr_dir/$KEY_REL_PATH
certificate     = $curr_dir/$CERT_REL_PATH

default_days    = 3650
# choose 512 as hash function
default_md      = sha512
preserve        = no
policy          = policy_strict

[ policy_strict ]
countryName             = match
stateOrProvinceName     = match
localityName            = match
organizationName        = match
organizationalUnitName  = optional
commonName              = supplied
emailAddress            = optional

[ req_distinguished_name ]
countryName                = $ENV_COUNTRY_OR_ZONE_NAME
stateOrProvinceName        = $ENV_STATE_OR_PROVINCE_NAME
localityName               = $ENV_LOCALITY_NAME
organizationName           = $ENV_ORGANIZATION_NAME
organizationalUnitName     = $ENV_ORGANIZATION_UNIT_NAME
commonName                 = $ENV_COMMON_NAME
emailAddress               = $ENV_EMAIL

[ req ]
ec_param_enc = explicit
ec_paramgen_curve = secp384r1
default_bits = 512
default_md = sha512
distinguished_name = req_distinguished_name
string_mask = utf8only
x509_extensions     = v3_ca
prompt              = no

[ v3_ca ]
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid:always,issuer
basicConstraints = critical, CA:true
keyUsage = critical, digitalSignature, cRLSign, keyCertSign

END_OF_STREAM
echo ">>>> ca.cnf is ready"


#### Generate CA key and set up privilege.        ####
## NOTICE: please remember the password you have typed
openssl genpkey -algorithm ED25519            \
                -aes256                       \
                -out "$KEY_REL_PATH"
chmod 444 "$KEY_REL_PATH"
echo ">>>> $KEY_REL_PATH is ready"

#### Generate CA certificate and set up privilege ####
openssl req -config ca.cnf                    \
            -key "$KEY_REL_PATH"              \
            -new -x509                        \
            -days 3650                        \
            -sha512 -extensions v3_ca         \
            -out "$CERT_REL_PATH"
chmod 444 "$CERT_REL_PATH"
echo ">>>> $CERT_REL_PATH is ready"

#### copy target to the share directory
# TODO: other distribution.
sudo -H --preserve-env sh -c "
    cp ./$CERT_REL_PATH /usr/local/share/ca-certificates/
    ln -s /usr/local/share/ca-certificates/$CERT_REL_PATH /etc/ssl/certs/$CERT_REL_PATH
    update-ca-certificates
"
echo ">>>> $CERT_REL_PATH is also added to /usr/local/share/ca-certificates/"

#### function may be useful
clean_cert_suits() {
    rm "/usr/local/share/ca-certificates/$CERT_REL_PATH" \
       "/etc/ssl/certs/$CERT_REL_PATH"
    rm -rf "$DEFAULT_PATH"
    update-ca-certificates
}
#### TODO: generate configuration definition as go file?
#### TODO: run different function according to passing arguments.
