on:
  push:
  pull_request:
    branches:
      - dev

name: UnitTest
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout branch
        uses: actions/checkout@v5

      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          check-latest: false

      - name: install other dependencies
        run: |
          sudo apt install make protoc-gen-go-grpc protoc-gen-go-1-5
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: test
        run: |
          make test-all
          if [ $? -ne 0 ]; then
            echo "UnitTest Failed!"
            exit 1
          fi

## solution 1
#      - name: Go Coverage Badge  # Pass the `coverage.out` output to this action
#        uses: tj-actions/coverage-badge-go@v3
#        with:
#          filename: coverage.out
#      - name: Verify Changed files
#        uses: tj-actions/verify-changed-files@v16
#        id: verify-changed-files
#        with:
#          files: docs/README.md
#
#      - name: Commit changes
#        if: steps.verify-changed-files.outputs.files_changed == 'true'
#        run: |
#          git config --local user.email "action@github.com"
#          git config --local user.name "GitHub Action"
#          git add README.md
#          git commit -m "chore: Updated coverage badge."
#
#      - name: Push changes
#        if: steps.verify-changed-files.outputs.files_changed == 'true'
#        uses: ad-m/github-push-action@master
#        with:
#          github_token: ${{ github.token }}
#          branch: ${{ github.head_ref }}

## solution 2
#      - name: Upload to Codecov
#        uses: codecov/codecov-action@v4
#        with:
#          file: ./coverage.out
#          fail_ci_if_error: true
#        env:
#          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
